In [2]:
import numpy as np

### **[실습] 다양한 방법으로 배열 생성**

<aside>
❓

NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.

1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열
5. *크기가 2x2인 정규 분포로 구성된 배열*
</aside>

In [19]:
arr1 = np.zeros((4,3))
print(arr1)
print('-----')

arr2 = np.ones((3,3))
print(arr2)
print('-----')

arr3 = np.arange(0,25,5)
print(arr3)
print('-----')

arr4 = np.linspace(0,1,4)
print(arr4)
print('-----')

arr5 = np.random.randn(2,2)
print(arr5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----
[ 0  5 10 15 20]
-----
[0.         0.33333333 0.66666667 1.        ]
-----
[[-0.09297825 -1.01108534]
 [ 1.20307307 -0.18677486]]


### **[실습 1] 인덱싱과 슬라이싱**

<aside>
❓

```python
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
```

1. 배열 `arr`에서 1번째 열만 추출
2. 배열 `arr`에서 2번째 행, 3번째 열의 값을 출력
3. 배열 `arr`에서 첫 번째 행부터 두 번째 행까지 선택하고, 0번째와 1번째 열만 추출
</aside>

In [31]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr[:,1])

print(arr[2,2])

print(arr[:2,:2])

[20 50 80]
90
[[10 20]
 [40 50]]


### [**실습 2] 팬시 인덱싱과 불리언 인덱싱**

<aside>
❓

```python
arr = np.array([10, 20, 30, 40, 50, 60, 70])
```

아래 배열에서 팬시 인덱싱과 불리언 인덱싱을 사용하여 다음 작업을 수행하세요.

1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
2. 배열의 값 중 50보다 큰 값만 추출
</aside>

In [ ]:
arr = arr = np.array([10, 20, 30, 40, 50, 60, 70])
idx = [0, 2, 4]
print(arr[idx])
print(arr[arr > 50])


[10 30 50]
[60 70]


### [bonus 1] arr = np.array([10, 20, 30, 40, 50) 일 때, 15 ~ 45 사이의 요소만 남겨서 출력하기

In [42]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[(arr >= 15) & (arr <=45)])

[20 30 40]


### [bonus2] arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 일 때, 짝수요소만 남기기

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr[arr%2 == 0])

[2 4 6 8]


### [**실습 3] 제품 판매 데이터 분석**

<aside>
❓

어느 마트에서 판매되는 제품들의 월별 매출량이 아래와 같이 주어졌습니다. 각각의 행은 제품을 나타내고, 열은 각 월의 판매량을 나타냅니다.

1. 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.
2. 3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.
3. 2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.
</aside>


In [81]:
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

print(sales[sales > 200])

print(sales[sales[:,2] <= 100, 0:2])

print(sales[sales[:,1] >= 150])

[220 300 320 310]
[[120 150]
 [ 50  45]]
[[120 150 100]
 [200 180 220]
 [300 320 310]]


### **[실습] 데이터를 기반으로 배열 연산 수행**

<aside>
❓

다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)
</aside>

In [79]:
sales1 = np.array([200, 340, 150, 400])
sales2 = np.array([220, 300, 180, 420])

a1 = sales1 + sales2
a2 = a1 / 2
print(a1)
print(a2)

[420 640 330 820]
[210. 320. 165. 410.]


### **[실습 1] 기본 산술 연산**

<aside>
❓

다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

</aside>

```python
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
```

In [83]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


### [**실습 2] Dot Product**

<aside>
❓

다음 두 배열 간의 내적 연산을 수행하세요.

</aside>

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
```

In [101]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.dot(arr1,arr2))
print(arr1 @ arr2)

32
32


### [**실습 3] 브로드캐스팅**

<aside>
❓

아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.

</aside>

```python
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])
```

In [85]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

print(arr2d+arr1d)

[[11 22 33]
 [14 25 36]]


### **[실습 4] 비교 연산 및 집계 함수 사용**

<aside>
❓

1. 배열에서 20보다 큰 값을 찾아 출력하세요.
2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.
</aside>

```python
arr = np.array([10, 20, 30, 40, 50])
```

In [106]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 20])
print(arr.sum())
print(arr.max())
print(arr.min())
print(arr.mean())


[30 40 50]
150
50
10
30.0


### **[실습 1] 중심 경향 및 산포 측도 계산**

<aside>
❓

아래 배열에서 평균, 중앙값, 최빈값, 분산, 표준편차, 범위를 계산하세요.

</aside>

```python
	arr = np.array([10, 20, 30, 30, 40, 50, 60])
```

In [140]:
from scipy import stats
arr = np.array([10, 20, 30, 30, 40, 50, 60])

print(np.mean(arr))
print(np.median(arr))
print(stats.mode(arr))
print(np.var(arr))
print(np.std(arr))
print(np.max(arr) - np.min(arr))

34.285714285714285
30.0
ModeResult(mode=np.int64(30), count=np.int64(2))
253.06122448979593
15.90789817951435
50


### [**실습 2] 정규분포와 균등분포의 난수 생성**

<aside>
❓

정규분포와 균등분포에서 각각 난수를 생성하여, 평균과 표준편차를 계산하세요.

1. 평균 0, 표준편차 1인 정규분포 난수 1000개 생성
2. 0과 1 사이의 균등분포 난수 1000개 생성
</aside>

In [114]:
arr1 = np.random.randn(1000)
print(np.mean(arr1), np.std(arr1))

arr2 = np.random.uniform(0,1,1000)
print(np.mean(arr2), np.std(arr2))

-0.00407108462687415 1.0203941334972393
0.4976215628416103 0.28958794038977365


### [**실습 3] 평균 성적 구하기**

<aside>
❓

아래와 같이 학생별 과목 성적 데이터가 주어졌을 때, 각 학생의 전체 평균 성적(수학, 영어, 과학)을 계산한 후, 이 평균값에 대한 분산과 표준편차를 구하세요.

</aside>

```python
# 학생별 과목 성적 데이터
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]
```

In [ ]:
# 내풀이

scores_math = np.array([88, 92, 76, 85, 95, 92, 88, 90, 85, 88])
scores_english = np.array([90, 85, 80, 87, 92, 89, 83, 91, 86, 88])
scores_science = np.array([85, 88, 82, 89, 94, 86, 91, 88, 84, 87])



student_mean = (scores_math + scores_english + scores_science)/3
print(student_mean.var(), student_mean.std())

11.89333333333335 3.4486712417006857


In [139]:
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]

student = np.array([scores_math, scores_english, scores_science])

print(np.mean(student,axis=0))
print(np.var(student,axis=0))
print(np.std(student,axis=0))


[87.66666667 88.33333333 79.33333333 87.         93.66666667 89.
 87.33333333 89.66666667 85.         87.66666667]
[ 4.22222222  8.22222222  6.22222222  2.66666667  1.55555556  6.
 10.88888889  1.55555556  0.66666667  0.22222222]
[2.05480467 2.86744176 2.49443826 1.63299316 1.24721913 2.44948974
 3.29983165 1.24721913 0.81649658 0.47140452]


### **[실습 1] 1차원 배열 정렬**

<aside>
❓

다음 1차원 배열을 오름차순 및 내림차순으로 정렬하세요.

</aside>

```python
arr = np.array([50, 10, 30, 40, 20])
```

In [143]:
arr = np.array([50, 10, 30, 40, 20])

arr_sort = np.sort(arr)
print(arr_sort)

arr_sort_desc = np.sort(arr)[::-1]
print(arr_sort_desc)

[10 20 30 40 50]
[50 40 30 20 10]


### [**실습 2] 2차원 배열 축 기준 정렬**

<aside>
❓

다음 2차원 배열을 행과 열을 기준으로 각각 정렬하세요.

</aside>

```python
arr2d = np.array([[8, 3, 5], [2, 9, 1]])
```

In [ ]:
arr2d = np.array([[8, 3, 5], [2, 9, 1]])
arr2d_sort0 = np.sort(arr2d,axis=0) # (열기준)
arr2d_sort1 = np.sort(arr2d,axis=1) # (행기준)

print(arr2d_sort0)
print(arr2d_sort1)

[[2 3 1]
 [8 9 5]]
[[3 5 8]
 [1 2 9]]


### **[실습 3] 인덱스를 반환하는 정렬**

<aside>
❓

다음 1차원 배열에서 정렬된 결과의 인덱스를 반환하고, 그 인덱스를 사용하여 배열을 정렬하세요.

</aside>

```python
arr = np.array([15, 10, 20])
```

In [ ]:
arr = np.array([15, 10, 20])
idx = np.argsort(arr)

print(idx)
print(arr[idx])

[1 0 2]
[10 15 20]


### **[실습 1] 1차원 배열 병합**

<aside>
💡

다음 두 개의 1차원 배열을 `np.concatenate()`와 `np.hstack()`을 사용하여 병합하세요.

</aside>

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
```

In [154]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr_concat = np.concatenate((arr1, arr2))
print(arr_concat)

arr_hstack = np.hstack((arr1, arr2))
print(arr_hstack)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


### **[실습 2] 2차원 배열 병합**

<aside>
💡

다음 두 개의 2차원 배열을 `np.concatenate()`와 `np.vstack()`을 사용하여 각각 병합하세요.

</aside>

```python
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
```

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr_concat = np.concatenate((arr1, arr2))
print(arr_concat)

arr_vstack = np.vstack((arr1, arr2))
print(arr_vstack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### **[실습 3] np.stack() 활용**

<aside>
💡

다음 두 개의 1차원 배열을 `np.stack()`을 사용하여 새로운 축을 따라 병합하세요.

</aside>

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
```

In [1]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr_stack_axis0 = np.stack((arr1, arr2),axis=0)
print(arr_stack_axis0)
arr_stack_axis1 = np.stack((arr1, arr2),axis=1)
print(arr_stack_axis1)

NameError: name 'np' is not defined

<aside>
❓

다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
3. 전체 지점에서 과일별 총 판매량을 구하고, 가장 많이 판매된 과일을 찾는다.
4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.
</aside>

- **데이터 (**각 지점의 월별 과일 판매량(단위: 개))
    
    ```python
    import numpy as np
    
    # 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
    # 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
    sales_data = np.array([
        # 지점 1
        [[120, 150, 200, 230, 180, 210],  # 사과 판매량
         [100, 140, 170, 190, 160, 180],  # 바나나 판매량
         [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량
    
        # 지점 2
        [[80, 90, 110, 140, 130, 120],
         [60, 70, 90, 100, 110, 95],
         [50, 80, 100, 110, 90, 85]],
    
        # 지점 3
        [[130, 140, 160, 180, 170, 190],
         [110, 120, 130, 150, 140, 160],
         [100, 110, 120, 130, 120, 140]],
    
        # 지점 4
        [[100, 130, 150, 170, 160, 180],
         [90, 100, 110, 120, 130, 125],
         [80, 110, 140, 130, 120, 110]],
    
        # 지점 5
        [[90, 110, 130, 140, 120, 130],
         [70, 85, 100, 110, 105, 95],
         [60, 90, 110, 100, 90, 95]]
    ])
    ```

In [1]:
import numpy as np
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])




# 1
store1_mean_for_month = np.mean((sales_data[:][0]),axis=0)
store2_mean_for_month = np.mean((sales_data[:][1]),axis=0)
store3_mean_for_month = np.mean((sales_data[:][2]),axis=0)
store4_mean_for_month = np.mean((sales_data[:][3]),axis=0)
store5_mean_for_month = np.mean((sales_data[:][4]),axis=0)
print(store1_mean_for_month)
print(store2_mean_for_month)
print(store3_mean_for_month)
print(store4_mean_for_month)
print(store5_mean_for_month)
print('----------------------------------------------------')
# 2
best_for_month1 = np.max((sales_data[:,:,0])) #각 차원에서 0번째 열의 가장큰값
best_for_month2 = np.max((sales_data[:,:,1])) #각 차원에서 1번째 열의 가장큰값
best_for_month3 = np.max((sales_data[:,:,2])) #각 차원에서 3번째 열의 가장큰값
best_for_month4 = np.max((sales_data[:,:,3])) #각 차원에서 4번째 열의 가장큰값
best_for_month5 = np.max((sales_data[:,:,4])) #각 차원에서 5번째 열의 가장큰값
best_for_month6 = np.max((sales_data[:,:,5])) #각 차원에서 6번째 열의 가장큰값
print(best_for_month1)
print(best_for_month2)
print(best_for_month3)
print(best_for_month4)
print(best_for_month5)
print(best_for_month6)
print('----------------------------------------------------')
# 3
# total_sales_for_fruits = np.

print(np.sum(sales_data[:]))

[103.33333333 136.66666667 176.66666667 186.66666667 156.66666667
 180.        ]
[ 63.33333333  80.         100.         116.66666667 110.
 100.        ]
[113.33333333 123.33333333 136.66666667 153.33333333 143.33333333
 163.33333333]
[ 90.         113.33333333 133.33333333 140.         136.66666667
 138.33333333]
[ 73.33333333  95.         113.33333333 116.66666667 105.
 106.66666667]
----------------------------------------------------
130
150
200
230
180
210
----------------------------------------------------
11115


In [ ]:
sales_data.shape #지점, 과일, 개월

(5, 3, 6)

In [ ]:
# 1. 각지점에서 사과, 바나나, 오렌지의 평균 판매량
avg_sales = np.mean(sales_data,axis=2) # axis 출을 기준으로 묶기

print(avg_sales)
print(avg_sales.shape) # 5개 지점의 3가지 과일 평균

[[181.66666667 156.66666667 131.66666667]
 [111.66666667  87.5         85.83333333]
 [161.66666667 135.         120.        ]
 [148.33333333 112.5        115.        ]
 [120.          94.16666667  90.83333333]]
(5, 3)


In [ ]:
# 2. 각 월마다 전체 지점에서 가장

total_sales = np.sum(sales_data, axis=2)

# 각월마다 가장 높은 판매량
max_sales = np.max(total_sales, axis=0)

# 각 월마다 가장많이 팔린 과일의 index

max_sales_indices = np.argmax(total_sales, axis=0)

fruits = ["사과", '바나나','오렌지']

for i, max_sale in enumerate(max_sales):
    fruits_name = fruits[max_sales_indices[i]]
    print()

In [ ]:
# 전체 지점에서 과일별 총 판매량을 구하고, 가장 많이 판매된 과일을 찾는다.

# axis = (0,2) 는 index 0 지점과 index 2 월을 합산하여 과일축만 남겨 합산
total_sales = np.sum(sales_data, axis= (0,2))
print("과일별 총 판매량 :", total_sales)

max_sales_index = np.argmax(total_sales) #argmax() : 가장 큰 값의 인덱스
max_sales_value = total_sales[max_sales_index]

fruits = ["사과", '바나나','오렌지']

print(f"가장 많이 판매된 과일 index : {max_sales_index}")
print(f"가장 많이 판매된 과일 : {fruits[max_sales_index]}, 총 판매량 : {max_sales_value}")

과일별 총 판매량 : [4340 3515 3260]
가장 많이 판매된 과일 index : 0
가장 많이 판매된 과일 : 사과, 총 판매량 : 4340


In [ ]:
# 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력

high_sales = sales_data >= 150
print(high_sales)

# where() : True 조건에 해당하는 인덱스 추출
# 각 인덱스별 지점, 과일, 월이 매칭된다.
# high_sales_indices[0] = 지점 인덱스
# high_sales_indices[1] = 과일 인덱스
# high_sales_indices[2] = 월 인덱스
high_sales_indices = np.where(high_sales)
print(f"high_sales_indices : {high_sales_indices}")

fruits = ["사과", '바나나','오렌지']

print("판매량 150개 이상인 데이터")
print(sales_data[high_sales])


for branch_idx, fruit_idx, month_idx in zip(*high_sales_indices):
    branch = branch_idx + 1
    month = month_idx + 1
    fruit_name = fruits[fruit_idx]
    sales = sales_data[branch_idx,fruit_idx,month_idx]
    
    print(f"{month}월 지점{branch} 과일: {fruit_name}")


[[[False  True  True  True  True  True]
  [False False  True  True  True  True]
  [False False  True False False  True]]

 [[False False False False False False]
  [False False False False False False]
  [False False False False False False]]

 [[False False  True  True  True  True]
  [False False False  True False  True]
  [False False False False False False]]

 [[False False  True  True  True  True]
  [False False False False False False]
  [False False False False False False]]

 [[False False False False False False]
  [False False False False False False]
  [False False False False False False]]]
high_sales_indices : (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3]), array([0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]), array([1, 2, 3, 4, 5, 2, 3, 4, 5, 2, 5, 2, 3, 4, 5, 3, 5, 2, 3, 4, 5]))
판매량 150개 이상인 데이터
[150 200 230 180 210 170 190 160 180 160 150 160 180 170 190 150 160 150
 170 160 180]
2월 지점1 과일사과
3월 지점1 과일사과
4월 지점1 과일사과
5월 지점1 과일사과


In [1]:
import pandas as pd
pd.__version__

'3.0.3'