In [5]:
import numpy as np
print(np.__version__)

2.5.0


In [8]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
b = np.array([4,5,6])
c = a + b
print(c)

[5 7 9]


In [12]:
print(a.shape) # 몇행 몇열
print(a.size) 

(3,)
3


In [13]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [15]:
arr = np.zeros((2, 3))  # 2x3 배열 (0으로 채운)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
arr = np.ones((3, 2))  # 3x2 배열 (1로 채운)
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [69]:
arr = np.arange(0, 10, 2)  # 0부터 9까지 2씩 증가하는 값
print(arr)

[0 2 4 6 8]


In [18]:
arr = np.linspace(0, 1, 5)  # 0에서 1까지 5개의 등간격 값
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [68]:
arr = np.random.randn(2, 3)  # 2x3 배열 정규 분포로 난수 배열 생성(평균0, 표준편차1)
print(arr)

[[-1.0090593   0.41241377  0.41411182]
 [-2.27488283 -0.87093357 -1.58348557]]


### 3**-2-3. ndarray 속성**

1. **shape : 배열의 모양**
    
    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print(arr.shape)  # (2, 3)
    ```
    
2. **dimension : 배열의 차원**
    
    ```python
    print(arr.ndim)  # 2차원 배열
    ```
    
3. **size : 배열의 크기**
    
    ```python
    print(arr.size)  # 총 6개의 원소
    ```
    
4. **배열의 데이터 타입 확인**
    
    ```python
    print(arr.dtype)  # int64
    ```

In [70]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)

print(arr.ndim)  # 2차원 배열

print(arr.size)  # 총 6개의 원소

print(arr.dtype)  # int64

(2, 3)
2
6
int64


In [72]:
# 1차원 배열 인덱싱
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # 0번째 요소 출력 (10)
print(arr[2])  # 2번째 요소 출력 (30)

10
30


In [76]:
# 2차원 배열 인덱싱
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0, 1])  # 0번째 행, 1번째 열의 요소 출력 (2)
print(arr[2, 2])  # 2번째 행, 2번째 열의 요소 출력 (9)

# 2차원 배열 슬라이싱
print(arr[1:, :2])  # 1번째 행부터 끝까지, 0번째와 1번째 열만 출력 ([[4, 5], [7, 8]])

2
9
[[4 5]
 [7 8]]


In [75]:
# 3차원 배열 인덱싱
arr = np.array(
    [
        [
            [1, 2, 3], 
            [4, 5, 6]
        ], 
        [
            [7, 8, 9], 
            [10, 11, 12]
        ]      
    ]   
)
print(arr[1, 0, 2])  # 1번째 차원, 0번째 행, 2번째 열의 요소 출력 (9)


# 3차원 배열 슬라이싱
print(arr[:, 1, :2])  # 각 차원에서 1번째 행의 처음 두 열 출력 ([[4, 5], [10, 11]])

9
[[ 4  5]
 [10 11]]


### 정수 배열을 사용한 펜시 인덱싱

In [77]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # 0번째, 2번째, 4번째 인덱스를 선택
print(arr[idx])   # [10, 30, 50]

[10 30 50]


### 2차원 배열에서 팬시 인덱싱

In [80]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = [0, 1, 2]
cols = [2, 1, 0]
print(arr[rows, cols])  # 각 행과 열을 묶어서 [(0, 2), (1, 1), (2, 0)]
print(arr[[0, 1, 2], [2, 1, 0]])

[3 5 7]
[3 5 7]


In [83]:
# 불리언 인덱싱
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 30]) # 조건에 맞는값 추출

[40 50]


In [84]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[arr > 4])  # [5, 6, 7, 8, 9]

[5 6 7 8 9]


# ndarray 연산

In [86]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** 2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


## 내적연산

In [88]:
# 리스트와 numpy ndarray 연산 차이
print([1,2,3] * 2)
print(np.array([1,2,3])*2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [89]:
# dot : 두 배열의 각원소를 곱한후 그 결과를 모두더함
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.dot(arr1, arr2)) # 1*4 + 2*5 + 3*6 = 32

32


In [91]:
arr2d = np.array([[1, 2], [3, 4]])
arr1d = np.array([5, 6])
print(np.dot(arr2d, arr1d))
# [1*5 + 2*6, 3*5 + 4*6]


[17 39]


In [ ]:
# 행렬곱
arr2d_1 = np.array([[1, 2], [3, 4]])
arr2d_2 = np.array([[5, 6], [7, 8]])
print(np.dot(arr2d_1, arr2d_2))
# [[1*5 + 2*7, 1*6 + 2*8],
#  [3*5 + 4*7, 3*6 + 4*8]]

print(arr2d_1 @ arr2d_2)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


 ###  브로드캐스팅(Broadcasting)**

- 브로드캐스팅은 서로 다른 크기의 배열 간 연산을 가능하게 하는 기능이다. NumPy는 작은 배열을 큰 배열의 크기에 맞춰서 연산을 수행할 수 있게 한다.

1. **스칼라 값과의 연산**
    - 배열 전체에 스칼라 값을 적용하여 연산할 수 있다.

In [102]:
arr = np.array([1, 2, 3])
print(arr + 10)  # [11, 12, 13]

[11 12 13]


2. **다차원 배열과 1차원 배열 간의 브로드캐스팅**
    - 다차원 배열에 1차원 배열을 브로드캐스팅 하여 연산할 수 있다.

In [103]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([1, 2, 3])
print(arr2d + arr1d)

[[2 4 6]
 [5 7 9]]


3. **3차원 배열과 2차원 배열 간의 브로드캐스팅**

In [105]:
arr3d = np.random.rand(3, 1, 4)  # 3x1x4 배열
arr2d = np.random.rand(4, 4)     # 4x4 배열

# 브로드캐스팅을 통해 3차원 배열과 2차원 배열 간 연산 수행
result = arr3d + arr2d
print(result.shape)  # 결과: 3x4x4 배열

(3, 4, 4)
[[[1.07199326 1.34836624 1.15369907 0.87463952]
  [1.25134431 0.76039375 0.46115315 1.64953867]
  [1.44093122 1.72440464 0.56095982 1.2283612 ]
  [0.87919696 1.2074723  0.53850438 1.40184294]]

 [[1.25282671 1.20269425 1.77296237 0.84351376]
  [1.43217777 0.61472177 1.08041645 1.61841292]
  [1.62176467 1.57873265 1.18022312 1.19723545]
  [1.06003042 1.06180032 1.15776767 1.37071719]]

 [[0.86274481 0.82558171 1.74462537 0.14231684]
  [1.04209587 0.23760923 1.05207944 0.91721599]
  [1.23168277 1.20162011 1.15188611 0.49603852]
  [0.66994852 0.68468778 1.12943067 0.66952026]]]


In [107]:
arr2d = np.array([[1,2,3],[4,5,6]])
row = np.array([10,20,30])
col = np.array([[10],[20]])
print(arr2d.shape, row.shape, col.shape)

(2, 3) (3,) (2, 1)


In [108]:
print(arr2d + row)
print(arr2d + col)

[[11 22 33]
 [14 25 36]]
[[11 12 13]
 [24 25 26]]


### 3 **-4-4. 비교 연산**

- 비교 연산을 사용하여 배열 내 각 요소가 조건을 만족하는지 확인할 수 있다.

In [110]:
arr = np.array([10, 20, 30])
print(arr > 15) 
print('-------')
print(arr == 20)  
print(arr != 20)  

print('-------')
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 2])
print(arr1 > arr2)  

[False  True  True]
-------
[False  True False]
[ True False  True]
-------
[False False  True]


### 3**-4-5. 집계 함수**

- NumPy는 배열의 각 요소에 대해 집계(aggregation) 연산을 수행할 수 있는 다양한 함수를 제공한다.
1. **합계(sum)**
    
    ```python
    arr = np.array([1, 2, 3, 4, 5])
    print(arr.sum())  # 15
    ```
    
2. **최대값/최소값(max/min)**
    
    ```python
    print(arr.max())  # 5
    print(arr.min())  # 1
    ```
    
3. **평균(mean)**
    
    ```python
    print(arr.mean())  # 3.0
    ```

4. **표준편차/분산(std/var)**
    
    ```python
    print(arr.std())  # 표준편차
    print(arr.var())  # 분산
    ```
    
5. **누계(cumsum)**
    
    ```python
    print(arr.cumsum())  # [1, 3, 6, 10, 15]
    ```
    
6. **축(axis)을 기준으로 한 연산**
    - 2차원 이상의 배열에서는 축(axis) 을 기준으로 연산을 수행할 수 있다.
    - 축 0은 행(row) 을 따라 연산을 수행하고, 축 1은 열(column) 을 따라 연산을 수행한다.

In [111]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d.sum(axis=0))  # [5, 7, 9] (각 열의 합)
print(arr2d.sum(axis=1))  # [6, 15] (각 행의 합)

[5 7 9]
[ 6 15]


### 3-5-4. 중심 경향 측도

In [116]:
arr = np.array([10, 20, 30, 40])
print(np.mean(arr)) 

# 중앙값
print(np.median(arr))


25.0
25.0


In [121]:
from scipy import stats

# 최빈값
arr = np.array([10, 20, 20, 30, 40])
print(stats.mode(arr))

ModeResult(mode=np.int64(20), count=np.int64(2))


### 정규분포

In [145]:
arr = np.random.randn(1000)  # 평균 0, 표준편차 1인 정규분포 난수 1000개
print(np.mean(arr), np.std(arr))

-0.00820204791892934 0.953233311005334


### 균등분포

In [146]:
arr = np.random.uniform(0, 1, 1000)  # 0과 1 사이의 균등분포 난수 1000개
print(np.mean(arr), np.std(arr))

0.4871119137144244 0.29025777323295054


# ndarray 정렬

In [148]:
arr = np.array([30, 10, 20, 40, 50])
sorted_arr = np.sort(arr)
print(sorted_arr) 

# 내림차순
sorted_arr_desc = np.sort(arr)[::-1]
print(sorted_arr_desc)  

[10 20 30 40 50]
[50 40 30 20 10]


In [149]:
# 2차원 배열 정렬
arr2d = np.array([[5, 2, 3], [8, 4, 1]])
sorted_arr2d = np.sort(arr2d)  # 행 단위로 정렬
print(sorted_arr2d)


[[2 3 5]
 [1 4 8]]


In [151]:
# 축 0을 기준으로 정렬 (열기준)
sorted_arr_axis0 = np.sort(arr2d, axis=0)
print(sorted_arr_axis0)

# 축 1을 기준으로 정렬 (행기준)
sorted_arr_axis1 = np.sort(arr2d, axis=1)
print(sorted_arr_axis1)


[[5 2 1]
 [8 4 3]]
[[2 3 5]
 [1 4 8]]


### **3-6-3. 인덱스를 반환하는 정렬 (argsort)**

- **`np.argsort()` 함수**는 배열을 정렬한 결과의 **인덱스 배열**을 반환한다. 이 인덱스를 사용하여 배열을 정렬할 수 있다.
1. **1차원 배열에서 argsort 사용**

In [152]:
arr = np.array([30, 10, 20])
sorted_indices = np.argsort(arr)
print(sorted_indices)  # (정렬된 순서의 인덱스)

# 인덱스를 사용하여 배열을 정렬
print(arr[sorted_indices]) 

[1 2 0]
[10 20 30]


2. **2차원 배열에서 argsort 사용**

In [156]:
arr2d = np.array([[3, 1, 2], [6, 4, 5]])
sorted_indices = np.argsort(arr2d, axis=1)  # 각 행을 기준으로 인덱스를 반환
print(sorted_indices)

[[1 2 0]
 [1 2 0]]


## **3-7. ndarray 병합**

### **3-7-1. 배열 병합이란**

<aside>
💡

배열 병합은 여러 개의 배열을 연결하여 하나의 배열로 만드는 방법이다. NumPy에서 배열을 병합하는 방법은 `np.concatenate()`, `np.vstack()`, `np.hstack()` 등의 함수를 사용한다.

</aside>

### **3-7-2. 축 기준 배열 병합**

- **`np.concatenate()`:** 주어진 축(axis)을 기준으로 배열을 병합하는 함수이다. 기본적으로 축 0을 기준으로 병합한다.

1. **1차원 배열 병합**
    - 두 개 이상의 1차원 배열을 연결할 수 있다.

In [157]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

merged_arr = np.concatenate((arr1,arr2))
print(merged_arr)

[1 2 3 4 5 6]


2. **2차원 배열 병합 (축 0)**
    - 행을 기준으로 배열을 병합할 수 있다. 이 경우 배열들의 열 개수가 같아야 한다.

In [161]:
arr1 = np.array([
    [1, 2], 
    [3, 4]
])
arr2 = np.array([
    [5, 6],
    [7, 8]
])
merged_arr = np.concatenate((arr1, arr2), axis=0)
print(merged_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


3. **2차원 배열 병합 (축 1)**
    - 열을 기준으로 배열을 병합할 수 있다. 이 경우 배열들의 행 개수가 같아야 한다.

In [160]:
merged_arr = np.concatenate((arr1, arr2), axis=1)
print(merged_arr)

[[1 2 5 6]
 [3 4 7 8]]


### **3-7-3. 수직 수평 배열 병합**

- **`np.vstack()`**: 수직으로 배열을 병합하는 함수로, 배열을 행(row) 기준으로 쌓는다. 여러 배열을 위아래로 병합할 수 있다.

In [166]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.vstack((arr1, arr2))
print(merged_arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


- **`np.hstack()`**: 수평으로 배열을 병합하는 함수로, 배열을 열(column) 기준으로 쌓는다. 여러 배열을 좌우로 병합할 수 있다.

In [167]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.hstack((arr1, arr2))
print(merged_arr)

[1 2 3 4 5 6]


### **3-7-4. 새로운 축을 따라 배열 병합**

- **`np.stack()`**: 새로운 축을 따라 배열을 병합하는 함수이다. 즉, 기존 배열에 차원을 추가한 후 그 축을 따라 배열을 쌓을 수 있다.
1. **0축을 따라 배열을 병합**

In [175]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

concat_arr = np.concatenate((arr1, arr2))
print("concat_arr :" ,merged_arr)
print('------------------')

vstack_arr = np.vstack((arr1, arr2))
print("vstack_arr :", vstack_arr)
print('------------------')

hstack_arr = np.hstack((arr1, arr2))
print("hstack_arr :", hstack_arr)
print('------------------')

stacked_arr_axis0 = np.stack((arr1, arr2), axis=0)
print("stacked_arr_axis0 :", stacked_arr_axis0)
print('------------------')


stacked_arr_axis1 = np.stack((arr1, arr2), axis=1)
print("stacked_arr_axis1 :", stacked_arr_axis1)



concat_arr : [1 2 3 4 5 6]
------------------
vstack_arr : [[1 2 3]
 [4 5 6]]
------------------
hstack_arr : [1 2 3 4 5 6]
------------------
stacked_arr_axis0 : [[1 2 3]
 [4 5 6]]
------------------
stacked_arr_axis1 : [[1 4]
 [2 5]
 [3 6]]


## **3-8. 심화 파트**

### **3-8-1. NumPy 성능 비교 및 최적화**

1. **Python 리스트와 NumPy 배열 성능 비교**
    - NumPy는 내부적으로 C 언어로 구현되어 있어, Python의 기본 리스트보다 훨씬 더 빠르고 메모리 효율적이다.
    - **Python 리스트의 성능 측정**

In [183]:
import time
size = 1000000
python_list = list(range(size))

start_time = time.time()
python_list = [x * 2 for x in python_list]
print("Python 리스트 성능:", time.time() - start_time)

Python 리스트 성능: 0.18698334693908691


In [184]:
np_array = np.arange(size)

start_time = time.time()
np_array = np_array * 2
print("NumPy 배열 성능:", time.time() - start_time)

NumPy 배열 성능: 0.007335662841796875


2. **벡터화(Vectorization)로 성능 최적화**
    - 반복문을 사용하지 않고 벡터화 연산으로 성능을 최적화한다.
    - **반복문을 사용하는 방식**

In [185]:
size = 1000000
python_list = list(range(size))
result = []

start_time = time.time()
for x in python_list:
    result.append(x * 2)
print("반복문 성능:", time.time() - start_time)

반복문 성능: 0.13121652603149414


In [186]:
np_array = np.arange(size)

start_time = time.time()
np_array = np_array * 2  # 벡터화 연산
print("벡터화 성능:", time.time() - start_time)

벡터화 성능: 0.01218867301940918


### **3-8-2. 메모리 사용 최적화**

- **배열의 데이터 타입 변경**
    - NumPy 배열의 데이터 타입은 배열이 사용하는 메모리 크기에 영향을 미친다. 적절한 데이터 타입을 선택하면 메모리 사용을 절감할 수 있다.
    - **기본 데이터 타입과 메모리 사용량 확인**

In [187]:
arr = np.array([1, 2, 3], dtype='int64')
print(arr.nbytes)  # 배열이 사용하는 메모리 크기 (bytes)

24


데이터 타입을 int32로 변경하여 메모리 절약

In [194]:
arr = np.array([1, 2, 3], dtype='int32')
print(arr.nbytes)  # 더 작은 메모리 사용

12


### **3-8-3. 대용량 데이터 처리**

1. **대용량 데이터로 연산 성능 테스트**
    - 대규모 배열로 NumPy 성능을 테스트하고, 처리 성능을 최적화할 수 있다.
    - **대용량 배열 생성 및 연산**

In [ ]:
size = 100_000_000  # 1억 개의 요소
arr = np.random.rand(size)  # 난수 배열 생성

start_time = time.time()
result = np.sum(arr)  # 배열의 합 계산
print("대용량 데이터 합계 성능:", time.time() - start_time)

대용량 데이터 합계 성능: 0.2747523784637451
50000844.226953454


2. **메모리 맵핑을 통한 대용량 파일 처리**
    - `np.memmap()`을 사용하면, 전체 데이터를 메모리에 올리지 않고 파일로부터 필요한 부분만 메모리에 로드해 작업을 수행할 수 있다.
    - **메모리 맵핑을 사용하여 파일 읽기**

In [198]:
# 1GB 크기의 파일을 생성 후 메모리 맵핑 방식으로 읽기
size = 10**9
arr = np.memmap('large_file.dat', dtype='float32', mode='w+', shape=(size,))
arr[:100] = np.random.rand(100)  # 일부 데이터를 파일에 쓰기

# 파일을 메모리 맵핑하여 읽기
memmap_arr = np.memmap('large_file.dat', dtype='float32', mode='r', shape=(size,))
print(memmap_arr[:10])  # 메모리에 로드된 일부 데이터만 접근

[0.43104333 0.00716878 0.6980336  0.91234076 0.64042586 0.2929806
 0.89775586 0.2881185  0.6912103  0.7314062 ]
