# fastText

https://github.com/facebookresearch/fastText

**FastText**는 자연어 처리(NLP) 작업에서 사용되는 오픈소스 라이브러리로, 텍스트 분류 및 단어 임베딩을 위한 빠르고 효율적인 도구이다. 이는 Facebook AI Research 팀에서 개발했으며, 특히 대규모 텍스트 데이터에서도 높은 성능과 속도를 제공한다.

FastText는 2016년에 Facebook AI Research(FAIR) 팀에 의해 처음 공개되었다.  
처음 발표된 논문은 **"Enriching Word Vectors with Subword Information"** (2016)이며, 이후 오픈소스로 GitHub에 공개되어 많은 사용자들에게 활용되고 있다.  

FastText는 Word2Vec 이후 등장한 모델로, 특히 서브워드 정보 활용과 텍스트 분류에서 효율성을 강조하면서 주목받았다.

**주요 특징**
1. **단어 벡터 학습 (Word Embeddings)**  
   - FastText는 단어를 고정된 크기의 벡터로 변환하는 단어 임베딩 모델을 학습한다. 이는 단어의 의미를 벡터 공간에 매핑하여 유사한 단어가 가까운 벡터로 표현되도록 한다.
   - 기존의 Word2Vec과 유사하지만, FastText는 단어를 **서브워드(subword)** 단위로 처리한다.

2. **서브워드 기반 모델 (Subword-based Model)**  
   - 단어를 n-그램(예: 'apple' → ['app', 'ppl', 'ple'])으로 분해하여 학습하기 때문에, **희귀 단어**나 **철자 오류**에도 강건하다.
   - 이는 단어 외에도 철자 패턴과 같은 더 세밀한 정보를 학습하는 데 유용하다.

3. **텍스트 분류 (Text Classification)**  
   - FastText는 문서나 문장을 빠르고 정확하게 분류하는 데 최적화되어 있다.
   - 학습 과정이 빠르고, 모델의 크기가 작으며, 정확도도 뛰어나다.

4. **효율적인 구현**  
   - FastText는 CPU 기반으로도 높은 성능을 내도록 설계되었으며, 대규모 데이터셋에서도 빠르게 작동한다.

**FastText의 작동 원리**
1. **단어 표현**  
   - 단어를 n-그램 서브워드로 나눈 후, 각 서브워드에 대해 벡터를 학습한다.
   - 예를 들어, "cat"이라는 단어는 'c', 'ca', 'cat'과 같은 다양한 조합으로 분해된다.
   - 결과적으로 단어 벡터는 각 서브워드 벡터의 합으로 표현된다.

2. **모델 구조**  
   - FastText는 Skip-gram 모델이나 CBOW 모델을 기반으로 동작한다.
   - 단, 기존 모델과 달리 단어 자체가 아닌 서브워드를 사용하여 학습한다.

**FastText의 장점**
1. **희귀 단어 처리 능력**  
   - 서브워드 기반 접근 방식 덕분에 희귀 단어 또는 새로운 단어에 대해 더 좋은 일반화 성능을 발휘한다.
2. **빠른 학습 속도**  
   - 단순한 모델 구조와 최적화된 구현으로 매우 빠르게 학습할 수 있다.
3. **다양한 언어 지원**  
   - 다양한 언어에서 동작하며, 특히 굴절어(inflected languages)와 같은 복잡한 언어에서도 효과적이다.

**활용 사례**
1. **단어 임베딩**  
   - 단어 간 유사도 계산, 문장 표현 학습.
2. **텍스트 분류**  
   - 스팸 필터링, 감정 분석, 뉴스 분류.
3. **다언어 지원**  
   - 다국어 데이터셋에서 빠른 응답 성능 제공.

In [1]:
!gdown https://drive.google.com/uc?id=1vyZuUgbejAnx8xicQnQ1HgtW6avN8ZRQ

Downloading...
From (original): https://drive.google.com/uc?id=1vyZuUgbejAnx8xicQnQ1HgtW6avN8ZRQ
From (redirected): https://drive.google.com/uc?id=1vyZuUgbejAnx8xicQnQ1HgtW6avN8ZRQ&confirm=t&uuid=a8a9bd08-2cb7-4f41-af8c-71bf14c3b892
To: c:\Users\MoonSungHo\skn34-st\study\NLP\03\ted_en-20160408.xml

  0%|          | 0.00/74.5M [00:00<?, ?B/s]
  1%|          | 524k/74.5M [00:00<00:24, 3.08MB/s]
  3%|▎         | 2.10M/74.5M [00:00<00:10, 6.81MB/s]
  6%|▋         | 4.72M/74.5M [00:00<00:05, 12.5MB/s]
 10%|▉         | 7.34M/74.5M [00:00<00:04, 15.8MB/s]
 13%|█▎        | 9.44M/74.5M [00:00<00:04, 14.6MB/s]
 15%|█▌        | 11.5M/74.5M [00:00<00:04, 14.6MB/s]
 18%|█▊        | 13.1M/74.5M [00:00<00:04, 14.8MB/s]
 20%|█▉        | 14.7M/74.5M [00:01<00:04, 14.0MB/s]
 22%|██▏       | 16.3M/74.5M [00:01<00:04, 14.1MB/s]
 25%|██▍       | 18.4M/74.5M [00:01<00:04, 13.6MB/s]
 27%|██▋       | 19.9M/74.5M [00:01<00:03, 13.9MB/s]
 29%|██▉       | 21.5M/74.5M [00:01<00:03, 13.4MB/s]
 31%|███       | 23.1

In [2]:
import nltk

nltk.download('punkt')  # NLTK 토크나이저
nltk.download('punkt_tab') # punkt 관련 테이블리소스
nltk.download('stopwords') # 불용어 목록

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\MoonSungHo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\MoonSungHo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\MoonSungHo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
from lxml import etree  # XML 파싱 / 검색 도구

xml = open('ted_en-20160408.xml', 'r', encoding= 'UTF8')    
tree = etree.parse(xml)     # xml파일을 파싱해서 트리구조로 로드

content = tree.xpath('//content/text()')    # Xpath로 모든 <content> 태그의 텍스트 추출
print(len(content))

corpus = '\n'.join(content)     # 하나이 텍스트 코퍼스로 생성

2085


In [6]:
# 텍스트 정제 + 토큰화 + 불용어 제거
import re
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

corpus = re.sub(r'\([^)]*\ ','',corpus)     # 괄호 (...) 안 텍스트 제거
corpus = re.sub(r'[^a-z0-9\s.,!?]+','', corpus, flags= re.IGNORECASE)   # 영문대소문자/ 숫자/ 공백/ 구두점 제외 제거
corpus = corpus.lower()     # 소문자로 통일

en_stopwords = stopwords.words('english')   # 영어 불용어 리스트

sentences = sent_tokenize(corpus)   # 문장 리스트로 분리
normalized_sentences = []           # 문장별 정규화 토큰

for sent in sentences:
    tokens = word_tokenize(sent)    # 토큰 리스트로 분리    
    normalized_tokens = [token for token in tokens if token not in en_stopwords]    # 불룡어 제거
    normalized_sentences.append(normalized_tokens)
    
print(f'총 문장 수: {len(normalized_sentences)}')

총 문장 수: 271266


In [7]:
%%time  #실행시간을 함께 출력
from gensim.models.fasttext import FastText

# FastText : 단어를 서브워드까지 활용하여 임베딩 학습하는 모델
model = FastText(           
    normalized_sentences,   # 입력 문장별 토큰 리스트 (list[list(str)])
    vector_size = 100,      # 임베딩 차원
    window = 5,             # skip-gram1 => 중심 단어 기준 주변단어 5토큰 문맥 확인
    min_count = 5,          # 빈도 5미만인 단어는 어휘에서 제거
    workers = 4,            # CPU 사용 스레드 수
    sg=1                    # Skip-Gram 사용 (0이면 CBOW)
)

CPU times: total: 6min 36s
Wall time: 2min 34s


In [8]:
model.wv.vectors.shape

(22197, 100)

In [9]:
print(model.wv.most_similar('man'))
print(model.wv.most_similar('man', 'woman'))

[('woman', 0.8209946751594543), ('batman', 0.7962943911552429), ('hoffman', 0.7639785408973694), ('manju', 0.742572009563446), ('stuntman', 0.7400626540184021), ('lehman', 0.7387824058532715), ('shaman', 0.7378416657447815), ('roman', 0.7256097793579102), ('fireman', 0.7204692363739014), ('wurman', 0.7122262716293335)]
[('rock', 0.3228519558906555), ('rocks', 0.2850020229816437), ('magnet', 0.2765800952911377), ('magnets', 0.2764923870563507), ('mans', 0.24262431263923645), ('material', 0.23672552406787872), ('ropes', 0.23568519949913025), ('mash', 0.23431424796581268), ('wind', 0.2336781620979309), ('natural', 0.23322626948356628)]


In [18]:
# 처음 보는 단어도 vector 구성해줌
print(model.wv.get_index('apple'))          # apple 인덱스 확인
print(model.wv.vectors[1621][:5])           # 1620번째 인덱스의 벡터 앞 5개
print('---')
print(model.wv.get_vector('apple')[:5])     # apple의 벡터 앞 5개
print('---')
# print(model.wv.get_index('ultramicrosafe'))       # 사전에 없어서 오류
print(model.wv.get_vector('ultramicrosafe')[:5])    # 사전에 없어도 벡터생성

1621
[ 0.15414263  0.38869268 -0.01024057  0.29240587 -0.00040489]
---
[ 0.15414263  0.38869268 -0.01024057  0.29240587 -0.00040489]
---
[-0.05253169  0.3642352   0.0634316   0.02904121  0.05621044]


In [19]:
# FastText 임베딩 구성 확인: 단어 벡터 = (단어 자체 벡터 + 서브워드 벡터들 ) 평균
import numpy as np

word = 'apple'
word_vec = model.wv.get_vector(word)
print(word_vec[:5])

word_idx = model.wv.get_index(word)
print(word_idx)

base_vec = model.wv.vectors_vocab[word_idx]
print(base_vec[:5])

subword_index = model.wv.buckets_word[word_idx]
subword_vecs = model.wv.vectors_ngrams[subword_index]
print(subword_vecs.shape)
print(subword_vecs[:, :5])

calc_vec = np.vstack((base_vec, subword_vecs)).mean(axis= 0)
print(calc_vec[:5])

[ 0.15414263  0.38869268 -0.01024057  0.29240587 -0.00040489]
1621
[-0.17676435 -0.28850442  0.24497493 -0.2706493   0.07841364]
(14, 100)
[[ 0.12738617  1.111986    0.19777384  0.87929374 -0.3789463 ]
 [ 0.6086208   1.2867028  -0.19258486  0.69591916 -0.680519  ]
 [ 0.1548038   0.5237765  -0.17017713  0.46119165  0.2271911 ]
 [ 0.44730416 -0.04115107  0.11183043 -0.46525407  0.39343905]
 [-0.7449325  -0.25128943 -0.40271094  1.3750755  -1.6730644 ]
 [ 0.17938383  0.60118324 -0.42768478  0.6202201   0.17250025]
 [ 0.0173503  -0.27767974  0.12882371 -0.3216347   0.06017954]
 [-0.15776351 -0.21465912  0.13530385 -0.12528531  0.03862068]
 [-0.91814864  0.7747014  -0.3749245   0.15198246  1.2107744 ]
 [ 0.07348609 -0.13966891  0.14491664 -0.20623611  0.14362422]
 [-0.19327967 -0.14473945  0.13831747  0.00504596  0.01074412]
 [ 0.32579696  0.7488318  -0.86498165  0.92163074  0.37311247]
 [ 0.5267161   0.673271    0.53076833  0.5340789   0.25078434]
 [ 2.0421798   1.4676293   0.6467461   0.1

In [ ]:
# 문장벡터 : 문장 벡터도 단어와 같은 벡터 차원을 가짐
sent_vec = model.wv.get_sentence_vector('I love apple very much~')
sent_vec.shape

(100,)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

sentences = [
    'i love apple',
    'apple is good',
    'i hate banana',
    'banana is yellow'
]

# 각 문장을 학습된 모델로 문장 벡터로 변환(2D 배열)
sent_vec = np.array([model.wv.get_sentence_vector(sent) for sent in sentences])
print(sent_vec.shape)

sent_cos_sim = cosine_similarity(sent_vec)

pd.DataFrame(
    sent_cos_sim,
    columns= sentences,
    index = sentences
)

(4, 100)


,i love apple,apple is good,i hate banana,banana is yellow
i love apple,1.000000,0.911155,0.746592,0.896728
apple is good,0.911155,1.000000,0.684829,0.841264
i hate banana,0.746592,0.684829,1.000000,0.898165
banana is yellow,0.896728,0.841264,0.898165,1.000000


In [25]:
model.save('ted_en_fasttext.model') # FastText 로 학습한 결과(가중치/어휘/설정 포함)을 파일로 저장

In [26]:
model2 = FastText.load('ted_en_fasttext.model')

In [27]:
model2.wv.most_similar('woman')

[('womans', 0.8458792567253113),
 ('man', 0.8209946751594543),
 ('womanhood', 0.8075434565544128),
 ('hoffman', 0.7891099452972412),
 ('lehman', 0.7862024307250977),
 ('batman', 0.7745257019996643),
 ('fireman', 0.7671605944633484),
 ('stuntman', 0.747183620929718),
 ('joan', 0.7369037866592407),
 ('orphan', 0.7319225072860718)]