In [1]:
123

123

In [2]:
import torch

x= torch.FloatTensor([[1, 2],
                     [3, 4]]).requires_grad_(True)

requires_grad_(True) : 이 텐서에 대해서 미분값을 구하겠다(일반적인 학습에서는 사용안함. 기울기 분석용)

In [4]:
# x -> x1 -> x2 -> x3 -> y 연산트리 생성
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()

print(x1)
print(x2)
print(x3)
print(y)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)
tensor(14., grad_fn=<SumBackward0>)


In [ ]:
y.backward()  # y값을 기준으로 계산 그래프를 따라 연결된 모든 텐서의 기울기를 자동으로 계산

In [ ]:
print(x.grad)   # y에 대해 계산된 x의 기울기(∂y /∂x)

tensor([[2., 4.],
        [6., 8.]])


y = (x + 2) (x - 2) 모두 합치면 y= ∑(x^2 -4) 합    

∂/∂x(-4) = 0  
=> -4는 미분 결과에 영향을 주지 않음

∂/∂x_i(x^2)

$
\frac{\partial}{\partial x_i}(x_i^2) = 2x_i
$

벡터 형태로 보면 
$
\frac{\partial y}{\partial x} = 2x
$

결론적으로 x.grad 결과는 2x 형태로 나오게 된다.

In [7]:
print(x)    # 텐서값을 변경 없음, 역전파는 기울기를 계산만 하고, 수정하지 않음(기울기 추적 대상)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [9]:
x3.numpy()    # numpy는 autograd 상태를 모르기 때문에 바로 numpy 형태로 변환은 되지 않음

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [10]:
x3.detach_().numpy()

array([[-3.,  0.],
       [ 5., 12.]], dtype=float32)

detach()    : 복사본을 만들면서 분리  
detach_()   : 원본 자체를 분리 (detach() + inplace 옵션)

In [11]:
x2  # 추적중 확인

tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)

In [12]:
x3  # numpy 배열 형태로 출력

tensor([[-3.,  0.],
        [ 5., 12.]])