## 02-04. 출력층 설계

### 02-04-01. 출력층 활성화 함수

### 02-04-02. 항등 함수

- 항등 함수(Identity Function)는 입력 값을 그대로 출력하는 함수이다.


In [ ]:
import numpy as np


def identity_function(x):
    return x

x = np.array([1.0, 2.0, 3.0])
print(identity_function(x))

[1. 2. 3.]


회귀 문제도 신경망 내부에서 이미 은닉층을 거치면서 비선형 변환이 이루어진 상태이므로,  
출력층에서는 그냥 나오는 출력값 그대로 사용한다.

### 02-04-02. 시그모이드 함수

- 시그모이드 함수 (Sigmoid Function)는 이진 분류나 다중 레이블 분류 문제에서 주로 사용되는 활성화 함수이다.

In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.array([0.0, 2.0, -1.0])
print(sigmoid(x))

[0.5        0.88079708 0.26894142]


Sigmoid 함수로 나온 예측 확률을 임계값을 기준으로 예측 결과로서 결정

출력값 >= 0.5  -> 클래스 1
출력값 < 0.5  -> 클래스 0

- 활성화 함수로서 사용하지 않는 이유  
출력이 0또는 1에 가까워지면 기울기가 거의 0에 수렴되어 학습이 거의 되지 않아    
출력층에서만 사용한다.

손실함수로 BCE와 함께 사용

### 02-04-03. 소프트맥스 함수

- 소프트맥스(Softmax) 함수는 분류 문제에서 출력층에서 사용되는 활성화 함수이다.

In [8]:
def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

x = np.array([2.0, 1.0, 0.1])
print(softmax(x))

[0.65900114 0.24243297 0.09856589]


- 소프트맥스 함수 구현 시 주의점
    - 소프트맥스 함수는 지수 연산을 포함하기 때문에 오버플로우(Overflow) 문제가 발생할 수 있다.
    - 이를 방지하기 위해 입력에서 최대값을 빼는 기법을 적용한다.

In [15]:
def stable_softmax(x):
    x_max = np.max(x)
    exp_x = np.exp(x - x_max)  # 최대값을 빼서 안정적으로 변환
    return exp_x / np.sum(exp_x)

x = np.array([1000, 1001, 1002])  # 큰 값에서도 안정적으로 동작
print(stable_softmax(x))

[0.09003057 0.24472847 0.66524096]
