In [3]:
import torch

# Tensor 기본

In [4]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])

b = torch.FloatTensor([[1, 2],
                       [1, 2]])

c = torch.matmul(a, b)  # 행렬 곱

c

tensor([[ 3.,  6.],
        [ 7., 14.]])

In [5]:
d = a @ b  # 행렬곱

d

tensor([[ 3.,  6.],
        [ 7., 14.]])

1D X 1D => 내적 (np.dot)

In [6]:
a = torch.IntTensor([[1, 2],
                    [3, 4]])
a

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

IntTensor 도 선언 가능하지만 일반적으로 딥러닝에서 가중치, 출력값, 손실, 기울기 등 모든 연산이 실수 연산  
그래서 FloatTensor를 기본으로 사용한다.


In [7]:
b = torch.LongTensor([[1, 2],
                       [1, 2]])
b

tensor([[1, 2],
        [1, 2]])

In [8]:
c = torch.ByteTensor([[1, 2],
                    [3, 4]])
c

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [9]:
mask = torch.BoolTensor([True, False, True])
mask

tensor([ True, False,  True])

In [10]:
x = torch.FloatTensor(3, 2)     # shape이 3행 2열인 텐서
x

tensor([[-2.0314e+00,  8.7861e-43],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])

In [11]:
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [12]:
torch.ones(3,2)         # 3,2 형태의 1로 채워진 텐서

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [13]:
torch.randn(3,2)       # 3,2 형태의 정규분포 난수 텐서

tensor([[-1.3060, -0.4752],
        [-0.3748, -0.7229],
        [-1.7053,  0.0187]])

In [14]:
import numpy as np

x = np.array([[1, 2],
              [3, 4]])

print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [15]:
# Pytorch tensor 로 변환
x= torch.from_numpy(x)

print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [16]:
# pytorch tensor 를 numpy ndarray 형태로 변환
x= x.numpy()

print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [17]:
x= torch.from_numpy(x)

x.long()        # LongTensor(int 64) 타입으로 변환, 소수점 버림( 분류문제 정답라벨)

print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [18]:
x.float()   # FloatTensor(float32) 타입으로 변환

print(x,type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [19]:
torch.FloatTensor([1,0]).bool()     # BoolTensor 형태로 변환

tensor([ True, False])

In [20]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                        [[5,6],
                         [7,8]],
                        [[9,10],
                         [11,12]]])

print(x.size())     # pytorch 메서드
print(x.shape)      # numpy 스타일

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [21]:
print(x.dim())  # 텐서의 차원 수(3, 2, 2) -> 3차원

3


In [22]:
print(len(x.size()))    # 텐서의 길이 => 차원 수

3


In [23]:
# 텐서의 특정 차원에 있는 요소의 개수
print(x.size(1))    # size(인덱스)
print(x.shape[1])

2
2


In [24]:
# 마지막 차원 요소 개수
print(x.size(-1))    # 마지막 축
print(x.shape[-1])

2
2


# Tensor 연산

In [25]:
import torch

In [26]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])

b = torch.FloatTensor([[1, 2],
                       [1, 2]])

a + b

tensor([[2., 4.],
        [4., 6.]])

In [27]:
a - b

tensor([[0., 0.],
        [2., 2.]])

In [28]:
a ** b

tensor([[ 1.,  4.],
        [ 3., 16.]])

In [29]:
print(a)
print(b)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [1., 2.]])


In [30]:
print(a.mul(b))     # 제자리 곱 연산

tensor([[1., 4.],
        [3., 8.]])


In [31]:
print(a.mul_(b))    # _가 붙은 연산은 원본 Tensor를 바꿔주는 inplace 역할

tensor([[1., 4.],
        [3., 8.]])


In [32]:
a

tensor([[1., 4.],
        [3., 8.]])

In [33]:
print(a.sum())      # 전체의 합
print(a.mean())     # 전체 평균

tensor(16.)
tensor(4.)


In [34]:
print(a.sum(dim=0))     # 행 축을 따라 값들을 더함(행축은 사라진다)
print(a.sum(dim=1))     # 열 축을 따라 값들을 더함(열축은 사라진다)

tensor([ 4., 12.])
tensor([ 5., 11.])


Broadcat : 텐서의 차원(크기)이 다를 때, 자동으로 차원을 확장해 차원을 맞춰주는 기능

In [35]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])

print(x.shape, y.shape)

torch.Size([1, 2]) torch.Size([1, 2])


In [36]:
z = x + y
print(z, z.shape)

tensor([[ 5., 10.]]) torch.Size([1, 2])


In [37]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = 1

print(x.shape)

torch.Size([2, 2])


In [38]:
z = x + y           # y 가 자동 형변환이 이루어져 2, 2 행렬로 변환됨

print(z, z.shape)

tensor([[2., 3.],
        [4., 5.]]) torch.Size([2, 2])


``` 
1 -> ([[1, 1],
       [1, 1]]) 
```

x 와 동일한 shape 으로 브로드캐스팅 (자동 형변환)

In [39]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

y = torch.FloatTensor([3, 5])

print(x.shape, y.shape)

torch.Size([2, 2]) torch.Size([2])


In [40]:
z = x + y

print(z, z.shape)

tensor([[4., 7.],
        [6., 9.]]) torch.Size([2, 2])


``` 
[3, 5] -> ([[3, 5],
            [3, 5]]) 
```

x 의 행 수만큼 복제

In [41]:
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([[3],
                      [5]])

print(x.shape, y.shape)

torch.Size([1, 1, 2]) torch.Size([2, 1])


마지막 차원수 2로 같기 때문에 나머지 차원은 y에 없으므로 자동으로 1로 확장

In [42]:
z = x + y
print(z, z.shape)

tensor([[[4., 5.],
         [6., 7.]]]) torch.Size([1, 2, 2])


개수가 1인 차원은 확장된다.  
마지막 차원 2와 1 -> 1이 확장되어 2  
앞 차원 1과 2 -> 1이 확장되어 2  
=> (2, 2)

```
x 는 행방향으로 확장  
[[1, 2]] -> [[1, 2],  
            [1, 2]]

y 는 열방향으로 확장
[[3],   -> [[3, 3],
 [5]]       [5, 5]]
 

```

In [43]:
# 잘못 사용된 예시 

x = torch.FloatTensor([[[1, 2],
                        [4, 8]]])

y = torch.FloatTensor([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

print(x.shape, y.shape)

torch.Size([1, 2, 2]) torch.Size([3, 3])


In [44]:
z = x +y

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

0 번 차원 : x 는 1, y 는 없음  => 자동확장 가능상태  
1 번 차원 : x 는 2, y 는 3     => 다른데, 하나라도 1이면 가능하지만 둘다 1이 아님  
2 번 차원 : x 는 2, y 는 3     => 다른데, 하나라도 1이면 가능하지만 둘다 1이 아님  

브로드 캐스팅 조건 : 각 차원의 값이 같거나, 하나가 1 인 경우에만 자동 확장가능

# Tensor 조작하기 

In [ ]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
x.shape

torch.Size([3, 2, 2])

In [ ]:
print(x.reshape(12))     # shape을 명시적으로 지정 (12개 요소를 가진 1차원 텐서)
print(x.reshape(-1))     # -1 : 자동지정(자동 지정되는 갯수의 요소를 가진 1차원 텐서)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [ ]:
print(x.reshape(3, 4))      # 3행 4열로 바꾸기
print(x.reshape(3, -1))     # 3행 자동열로 바꾸기

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [ ]:
print(x.reshape(3, 4, 1))  
print(x.reshape(3, 2 ,-1)) 

tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.]],

        [[ 5.],
         [ 6.],
         [ 7.],
         [ 8.]],

        [[ 9.],
         [10.],
         [11.],
         [12.]]])
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


In [ ]:
print(x.reshape(-1, 2 ,-1))     # 자동 2개를 쓰면 안됌

RuntimeError: only one dimension can be inferred

In [ ]:
print(x.reshape(3,2,2,1))   # 2행 2열 + 채널 1이 붙은 데이터가 3개

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


view() : 연속된 메모리 구조일 때 사용  
reshape() : 필요시 데이터복사도 가능한 유연한 재구성 함수

In [ ]:
# squeeze() : 텐서에서 크기가 1인 차원 제거
x = torch.FloatTensor([[[1, 2],
                        [3, 4]]])
print(x.shape)

torch.Size([1, 2, 2])


In [ ]:
print(x.squeeze(), x.squeeze().size())

tensor([[1., 2.],
        [3., 4.]]) torch.Size([2, 2])


In [ ]:
# squeeze(차원) : 특정 차원을 제거한다. 크기가 1인 경우에만
print(x.squeeze(0).size())
print(x.squeeze(1).size())

torch.Size([2, 2])
torch.Size([1, 2, 2])


In [ ]:
# unsqueeze() : 특정 위치에 새로운 차원 추가
x = torch.FloatTensor([[1, 2],
                        [3, 4]])
print(x.shape)

torch.Size([2, 2])


In [ ]:
print(x.unsqueeze(2), x.unsqueeze(2).shape)     # 2번 차원

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]]) torch.Size([2, 2, 1])


In [ ]:
print(x.unsqueeze(-1), x.unsqueeze(-1).shape)   # 마지막차원

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]]) torch.Size([2, 2, 1])


차원 조작같은 경우 입력층 -> 은닉층  
또는                은닉층 -> 출력층 부분에서 차원을 맞춰서 값을 넘겨야 할때 주로 사용

# Tensor를 자르고 붙이기 (인덱싱, 슬라이싱)

In [52]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
x.shape

torch.Size([3, 2, 2])

In [53]:
print(x[0])     # 첫 번째 차원(dim= 0) 에서 인덱스 0 선택

print(x[0, :,  :])     # 생략된 차원을 명시적으로 표시


tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])


In [54]:
print(x[0, :])  # 첫 번째 차원(dim= 0) 에서 두번째 차원(dim= 1) 을 : (전체) 선택

tensor([[1., 2.],
        [3., 4.]])


뒤쪽 차원의 :(전체선택) 은 생략 가능하며, 생략하면 자동으로 :(전체) 처리된다

In [55]:
print(x[-1])    # 마지막 차원(dim = 0)에서 마지막 인덱스 선택

print(x[-1, :])     # 마지막 차원(dim = 0) 에서 두번째 차원(dim=1) 을 전체(:) 선택
print(x[-1, :, :])     # 생략된 차원을 명시적으로 표시

tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])


In [56]:
print(x[:, 0, :])   # 전체 배치에서 첫번째 행만 가져옴(열 전체)

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


In [57]:
print(x[, ,])

SyntaxError: invalid syntax (2200821247.py, line 1)

배치는 그대로 3 유지  
행은 선택되어 제거  
열은 그대로 2 유지

In [ ]:
# 슬라이싱으로 접근시 차원 수 유지
print(x[1:3, :, :])             # 배치가 1, 2 선택, 행과 열은 전체

tensor([[[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


In [ ]:
print(x[ : , :1 , : ], x[ : , :1 , : ].shape)   # 모든 배치. 행은 앞의 1개만 슬라이싱, 열은 전체

tensor([[[ 1.,  2.]],

        [[ 5.,  6.]],

        [[ 9., 10.]]]) torch.Size([3, 1, 2])


In [65]:
print(x[ : , :-1, : ], x[ : , :-1, : ].shape)     # 모든 배치. 행은 마지막 행 제외, 열은 전체

tensor([[[ 1.,  2.]],

        [[ 5.,  6.]],

        [[ 9., 10.]]]) torch.Size([3, 1, 2])


In [ ]:
x = torch.FloatTensor(10, 4)

x

tensor([[2.0785e+00, 8.7861e-43, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [87]:
# split() : 텐서를 원하는 모양으로 나눠준다

x = torch.zeros(10, 4)

x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
splits = x.split(4, dim=0)      # 0번 차원 기준으로 4개씩 자름 (split은 앞에부터 자름)

print(splits)

print(type(splits))


(tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]]))
<class 'tuple'>


In [ ]:

for split in splits:
    print(split.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [97]:
# chunk() : 텐서를 청크 수로 나눈다
x = torch.ones(8, 4)

chunks = x.chunk(4, dim= 0)     # 0번 차원 기준으로 3조각으로 나눔 (균등하게 나눔)

for chunk in chunks:
    print(chunk.size())

torch.Size([2, 4])
torch.Size([2, 4])
torch.Size([2, 4])
torch.Size([2, 4])


split(n, dim) : n개로 균등하게 분할 (크기)  
chunk(size, dim) : size 만큼 조각하여 자른다 (개수)

In [98]:
# index_select() : 차원 인덱스를 사용하여 요소를 선택

x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

indice = torch.LongTensor([2, 1])

x.size()

torch.Size([3, 2, 2])

In [ ]:
y = x.index_select(dim= 0 ,index= indice)   # 0번 차원 index가 indice 에서 지정한 순서대로 선택
                                            # [2, 1] -> x[2], 그다음 x[1] 선택
print(y, y.shape)   

tensor([[[ 9., 10.],
         [11., 12.]],

        [[ 5.,  6.],
         [ 7.,  8.]]]) torch.Size([2, 2, 2])


index_select 함수는 반환값이 있어 텐서가 새로 생성되어 사용시 값으로 받아준다.  
index 는 LongTensor 형태로 전달해준다.  

In [100]:
x.index_select(0, index=torch.LongTensor([0,0]))    # 인덱스 중복 선택

tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]]])

In [103]:
# cat() : 여러 텐서간의 연결

x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

y = torch.FloatTensor([[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]])

print(x.shape, y.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [ ]:
z = torch.cat([x, y], dim= 0)   # 차원0 (행기준)으로 합침
print(z, z.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]) torch.Size([6, 3])


cat() 으로 붙이는 축을 제외한 나머지 차원은 반드시 동일해야 이어 붙일 수 있다.  
2차원 Tensor 기준 dim= 0 :행 증가  
2차원 Tensor 기준 dim= 1 :열 증가

In [106]:
z = torch.cat([x, y], dim= 1)   # 차원1 (열기준)으로 합침
print(z, z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]]) torch.Size([3, 6])


In [ ]:
# stack() : 여러 텐서를 쌓아 새로운 차원을 만든다.
z= torch.stack([x,  y])     # x, y 2차원 데이터를 2장 쌓아 (2,3,3) 3차원으로 나타낸다.
print(z, z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]]) torch.Size([2, 3, 3])


cat() : 차원수 동일, 기존 축에 그대로 이어 붙임  
stack() : 차원수 +1. 새로운 축을 만들어 쌓음

In [110]:
print(torch.cat([x,  y]))
print(torch.stack([x,  y]))

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])


In [ ]:
z = torch.stack([x, y], dim= -1)    # 마지막 차원 추가 (feature, channel 차원 추가)

print(z,z.shape)

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]]) torch.Size([3, 3, 2])


# Pytorch 메서드

In [ ]:
# extend() : 크기가 1인 차원을 지정된 크기만큼 확장, 같은 값이 반복된 것처럼 보이게 해준다.
x= torch.FloatTensor([[[1,2]],
                      [[3, 4]]])
x.shape

torch.Size([2, 1, 2])

In [ ]:
y= x.expand(*[2, 3, 2])     # 기존 (2,1,2) 에서 행차원을 1 -> 3. 나머지 차원은 그대로 유지
            # * 리스트를 값으로 보낼때
print(y, y.shape)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]]) torch.Size([2, 3, 2])


expand()는 값을 복사하지는 않는다. 내부적으로 같은 메모리를 여러번 참조해서 사용  
- 메모리 효율성이 높다

값 앞에 * (unpacking) 은 list나 tuple의 값을 순차적으로 전달하기 위해 사용 

In [115]:
y= x.expand(2,3,2)
print(y, y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]]) torch.Size([2, 3, 2])


In [ ]:
# cat 을 활용하여 expand 구현하기
y = torch.cat([x, x, x], dim=1)     # dim= 1(두번째 차원) 기준으로 x를 3번 이어붙임

print(y, y.shape)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]]) torch.Size([2, 3, 2])


In [ ]:
# randperm() : 랜덤 순열. 0부터 n-1 까지의 정수를 무작위로 섞은 순열 텐서를 반환(특징 : 중복없음)

x= torch.randperm(10)
print(x, x.shape)

tensor([6, 8, 9, 1, 7, 2, 4, 5, 0, 3]) torch.Size([10])


In [122]:
x= torch.randperm(3**3).reshape(3, 3, -1)   # 0~ 26 27 개값, 3차원으로 구성
print(x, x.shape)

tensor([[[ 6, 25, 19],
         [ 8, 22,  0],
         [24,  1, 23]],

        [[12, 10,  2],
         [ 9, 18,  3],
         [13, 16,  7]],

        [[26, 17, 20],
         [14, 15, 21],
         [ 5,  4, 11]]]) torch.Size([3, 3, 3])


In [123]:
# argmax() : 최대값 인덱스 반환
y= x.argmax(dim = -1)   # 마지막 차원(열) 에서 가장 큰 값의 인덱스를 반환하고, 그 차원은 제거
print(y, y.size())

tensor([[1, 1, 0],
        [0, 1, 1],
        [0, 2, 2]]) torch.Size([3, 3])


argmax(dim= k) : k번 차원에서 가장 큰 인덱스를 선택하고, 그 차원 제거

In [124]:
y= x.argmax(dim= -1, keepdim=True) # 마지막 차원(열) 에서 가장 큰값의 인덱스를 반환하고, 차원 유지
print(y, y.size())

tensor([[[1],
         [1],
         [0]],

        [[0],
         [1],
         [1]],

        [[0],
         [2],
         [2]]]) torch.Size([3, 3, 1])


In [126]:
# topk() : 상위 k개의 값과 해당 인덱스를 튜플로 반환

values, indices = torch.topk(x, k=1, dim= -1)   # 마지막 차원 기준 상위 1개(k=1) 선택

print(values.size())
print(indices, indices.size())

torch.Size([3, 3, 1])
tensor([[[1],
         [1],
         [0]],

        [[0],
         [1],
         [1]],

        [[0],
         [2],
         [2]]]) torch.Size([3, 3, 1])


topk(k=1) 로 설정하면 argmax(keepdim= True) 와 같은 결과

In [131]:
x

tensor([[[ 6, 25, 19],
         [ 8, 22,  0],
         [24,  1, 23]],

        [[12, 10,  2],
         [ 9, 18,  3],
         [13, 16,  7]],

        [[26, 17, 20],
         [14, 15, 21],
         [ 5,  4, 11]]])

In [130]:
# topk를 이용해 정렬하기
target_dim = -1
values, indices = torch.topk(
    x,
    k=x.size(target_dim),   # 마지막 차원의 전체길이
    largest=True
    )

print(values, values.size())
print(indices, indices.size())

tensor([[[25, 19,  6],
         [22,  8,  0],
         [24, 23,  1]],

        [[12, 10,  2],
         [18,  9,  3],
         [16, 13,  7]],

        [[26, 20, 17],
         [21, 15, 14],
         [11,  5,  4]]]) torch.Size([3, 3, 3])
tensor([[[1, 2, 0],
         [1, 0, 2],
         [0, 2, 1]],

        [[0, 1, 2],
         [1, 0, 2],
         [1, 0, 2]],

        [[0, 2, 1],
         [2, 1, 0],
         [2, 0, 1]]]) torch.Size([3, 3, 3])


x[ i , j , : ]을 큰값 기준으로 내림차순 정렬
- 차원 수는 그대로 유지. 값의 순서만 바뀜(정렬)
- 각 줄에서는 큰값 -> 작은 값순으로 정렬

indices 는 정렬되기 전 위치 값  

결과적으로 topk(k= 차원크기) 를 주면 해당차원을 기주능로 값을 정렬한 효과를 얻는다

In [139]:
k = 1
values, indices = torch.sort(x, dim= -1, descending=True)   # 마지막 차원을 기주능로 내림차순 정렬(값, 원래위치)
values, indices = values[:, :, :k,], indices[:,:,:k]        # 정렬된 결과중 가장 큰 값 1개 선택(3,3,1)


print(values.squeeze(-1), values.squeeze(-1).size())
print(indices.squeeze(-1),indices.squeeze(-1).size())

tensor([[25, 22, 24],
        [12, 18, 16],
        [26, 21, 11]]) torch.Size([3, 3])
tensor([[1, 1, 0],
        [0, 1, 1],
        [0, 2, 2]]) torch.Size([3, 3])


sort + 슬라이싱 = topk 사용과 동일한 효과를 얻는다.



In [ ]:
# masked_fill() : 마스크가 True 인 위치에 지정한 값을 채움

x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)

print(x, x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]) torch.Size([3, 3])


In [142]:
mask = x>4
mask

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [ ]:
y= x.masked_fill(mask, value= -1)   # mask 가 True 인 위치를 -1로 채움

print(y, y.size())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]]) torch.Size([3, 3])


사용처 
- 이미지 처리 padding 처리
- loss 계산에서 해당 값 무시

In [144]:
# Ones, Zeros : 모든 요소가 0 또는 1로 채워진 텐서 반환

print(torch.ones(2,3))
print(torch.zeros(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [145]:
# ones_like(), zeros_like() : 기준 텐서와 동일한 형태의 초기화 텐서 반환

print(torch.ones_like(x))
print(torch.zeros_like(x))


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
